name: Generate Podcast Feeds
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repoooooooooooo
        uses: actions/checkout@v4.1.1
      - name: Run Fedddd Generator
        uses: umair-saeed/podcast-generator@main
